package com.cellexperts.db.hbm;

// Generated Sep 9, 2015 10:52:46 AM by Hibernate Tools 3.4.0.CR1

/**
 * DailyTimesheetDtls generated by hbm2java
 */
public class DailyTimesheetDtls implements java.io.Serializable {

	private DailyTimesheetDtlsId id;
	private EmployeeTimesheet employeeTimesheet;
	private String day;
	private double hours;
	private Long overtime;
	private boolean dayOff;
	private double cash;
	private String notes;
	private String lastuser;
	private double minutes; 
	
	public double getMinutes() {
		return minutes;
	}

	public void setMinutes(double minutes) {
		this.minutes = minutes;
	}

	public double getCash() {
		return cash;
	}

	public void setCash(double cash) {
		this.cash = cash;
	}

	public String getNotes() {
		return notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public String getLastuser() {
		return lastuser;
	}

	public void setLastuser(String lastuser) {
		this.lastuser = lastuser;
	}
	
	public DailyTimesheetDtls() {
	}

	public DailyTimesheetDtls(DailyTimesheetDtlsId id,
			EmployeeTimesheet employeeTimesheet) {
		this.id = id;
		this.employeeTimesheet = employeeTimesheet;
	}

	public DailyTimesheetDtls(DailyTimesheetDtlsId id,
			EmployeeTimesheet employeeTimesheet, String day, Long hours,
			Long overtime, boolean leave) {
		this.id = id;
		this.employeeTimesheet = employeeTimesheet;
		this.day = day;
		this.hours = hours;
		this.overtime = overtime;
		this.dayOff = leave;
	}

	public DailyTimesheetDtlsId getId() {
		return this.id;
	}

	public void setId(DailyTimesheetDtlsId id) {
		this.id = id;
	}

	public EmployeeTimesheet getEmployeeTimesheet() {
		return this.employeeTimesheet;
	}

	public void setEmployeeTimesheet(EmployeeTimesheet employeeTimesheet) {
		this.employeeTimesheet = employeeTimesheet;
	}

	public String getDay() {
		return this.day;
	}

	public void setDay(String day) {
		this.day = day;
	}

	public double getHours() {
		return this.hours;
	}

	public void setHours(double hours) {
		this.hours = hours;
	}

	public Long getOvertime() {
		return this.overtime;
	}

	public void setOvertime(Long overtime) {
		this.overtime = overtime;
	}

	public boolean getDayOff() {
		return this.dayOff;
	}

	public void setDayOff(boolean leave) {
		this.dayOff = leave;
	}

}
